"""Make an Adafruit GFX font header (1-bit, ASCII 0x20-0x7E) from a TTF/OTF at an exact
pixel size, for the info screen. Rendered with hinting and no antialiasing, so it stays
crisp on the 1-bit display.

    python tools/gfxfont.py FONT_FILE PIXEL_SIZE NAME src/fonts/NAME.h

Needs Pillow. The info screen's fonts come from Noto Sans (SIL Open Font License);
see src/fonts/README.md.
"""
import sys

from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 0x20, 0x7E


def build(font_file, size, name):
    font = ImageFont.truetype(font_file, size)
    ascent, descent = font.getmetrics()
    bits, glyphs = [], []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        adv = round(font.getlength(ch))
        if ch == " ":                                    # hinted small sizes squeeze words
            adv = max(adv, round(size * 0.3))
        # Draw on a roomy canvas and measure the real ink (getbbox can be the advance
        # box, which clips or shifts glyphs that overhang it). Drawn after a space:
        # Pillow shifts a lone glyph so its ink starts at the pen, which loses negative
        # side bearings (t, j, ...); mid-word it doesn't.
        ox, oy = size, 2 * size                          # pen position, on the baseline
        canvas = Image.new("1", (4 * size, 3 * size), 0)
        d = ImageDraw.Draw(canvas)
        d.fontmode = "1"                                 # hinted, no antialiasing
        d.text((ox, oy), " " + ch, font=font, fill=1, anchor="ls")
        ox += round(font.getlength(" "))
        ink = canvas.getbbox()
        offset = len(bits) // 8
        if ink:
            x0, y0, x1, y1 = ink
            w, h = x1 - x0, y1 - y0
            px = canvas.load()
            bits += [px[x, y] for y in range(y0, y1) for x in range(x0, x1)]
            while len(bits) % 8:                         # each glyph starts on a byte
                bits.append(0)
            glyphs.append((offset, w, h, adv, x0 - ox, y0 - oy, ch))
        else:
            glyphs.append((offset, 0, 0, adv, 0, 0, ch))

    # tabular digits: 0-9 share the widest advance, ink centred, so numbers that change
    # (uptime, counters) don't make the text around them shift
    digits = [i for i, g in enumerate(glyphs) if g[6].isdigit()]
    tab = max(glyphs[i][3] for i in digits)
    for i in digits:
        offset, w, h, adv, xo, yo, ch = glyphs[i]
        glyphs[i] = (offset, w, h, tab, (tab - w) // 2, yo, ch)

    data =bytes(int("".join(str(b) for b in bits[i:i + 8]), 2) for i in range(0, len(bits), 8))

    out = [f"// {name}: generated by tools/gfxfont.py from {font_file.split('/')[-1].split(chr(92))[-1]}"
           f" at {size} px. Do not edit.", "#pragma once", "#include <Adafruit_GFX.h>", "",
           f"static const uint8_t {name}Bitmaps[] PROGMEM = {{"]
    for i in range(0, len(data), 16):
        out.append("  " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    out += ["};", "", f"static const GFXglyph {name}Glyphs[] PROGMEM = {{"]
    for offset, w, h, adv, xo, yo, ch in glyphs:
        label = "'\\\\'" if ch == "\\" else repr(ch)
        out.append(f"  {{{offset:5d}, {w:3d}, {h:3d}, {adv:3d}, {xo:4d}, {yo:4d}}},  // {label}")
    out += ["};", "",
            f"static const GFXfont {name} PROGMEM = {{(uint8_t*){name}Bitmaps, (GFXglyph*){name}Glyphs,",
            f"                                     0x{FIRST:02X}, 0x{LAST:02X}, {ascent + descent}}};", ""]
    return "\n".join(out)


if __name__ == "__main__":
    if len(sys.argv) != 5:
        raise SystemExit(__doc__)
    font_file, size, name, path = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(build(font_file, size, name))
    print("wrote", path)
